// src/app/api/settings/group-filters/route.ts
import { NextResponse } from 'next/server';
import { logger } from '@/lib/logger';
import { prisma } from '@/lib/prisma';
import type { GroupFilter } from '@/types/settings'; // Our application-specific type
import { logAuditEvent } from '@/lib/auditLog';
import { authenticateAndTrackRequest } from '@/lib/auth-middleware';
import { Role } from '@/types/opnsense'; // Import Role enum

export async function GET(request: Request) {
  return authenticateAndTrackRequest(request, async (auth) => {
    // Require authentication and admin privileges for accessing group filters
    if (!auth.user) {
      return NextResponse.json({ error: 'Unauthorized: Authentication required to access group filters' }, { status: 401 });
    }

    // Check if user has admin privileges
    if (auth.user.role !== Role.ADMIN && auth.user.role !== Role.SUPER_ADMIN) {
      return NextResponse.json({ error: 'Forbidden: Admin privileges required to access group filters' }, { status: 403 });
    }

  try {
    const filterSettings = await prisma.groupFilterSetting.findMany({
      orderBy: {
        createdAt: 'desc',
      },
    });
    // Map Prisma model to our application type if they differ significantly
    // For now, assuming they are compatible enough or GroupFilterSetting is used directly
    const responseFilters: GroupFilter[] = filterSettings.map(dbFilter => ({
        id: dbFilter.id, // The DB id will be used
        pattern: dbFilter.pattern,
        description: dbFilter.description || '', // Ensure description is not null
        type: dbFilter.type as 'include' | 'exclude', // Assert type
    }));
    return NextResponse.json(responseFilters);
  } catch (error) {
    logger.error('Failed to fetch group filter settings:', error);
    return NextResponse.json({ error: 'Failed to fetch settings' }, { status: 500 });
  }
  });
}

export async function POST(request: Request) {
  return authenticateAndTrackRequest(request, async (auth) => {
    // Require authentication and admin privileges for modifying group filters
    if (!auth.user) {
      return NextResponse.json({ error: 'Unauthorized: Authentication required to access group filters' }, { status: 401 });
    }

    // Check if user has admin privileges
    if (auth.user.role !== Role.ADMIN && auth.user.role !== Role.SUPER_ADMIN) {
      return NextResponse.json({ error: 'Forbidden: Admin privileges required to modify group filters' }, { status: 403 });
    }

  const userId = auth.user?.id || null;
  const ipAddress = request.headers.get('x-forwarded-for') || null;
  const userAgent = request.headers.get('user-agent') || null;

  try {
    const newFilters: GroupFilter[] = await request.json();

    if (!Array.isArray(newFilters)) {
      return NextResponse.json({ error: 'Invalid input: Expected an array of filters.' }, { status: 400 });
    }

    // Validate each filter (basic validation)
    for (const filter of newFilters) {
      if (!filter.pattern || !filter.type || (filter.type !== 'include' && filter.type !== 'exclude')) {
        return NextResponse.json({ error: `Invalid filter object: ${JSON.stringify(filter)}` }, { status: 400 });
      }
    }

    // Fetch existing filters before deleting
    const oldFilters = await prisma.groupFilterSetting.findMany({
      orderBy: {
        createdAt: 'desc',
      },
    });

    // "Replace all" strategy: delete existing and create new ones
    await prisma.$transaction(async (tx) => {
      await tx.groupFilterSetting.deleteMany({}); // Delete all existing filters
      if (newFilters.length > 0) {
        await tx.groupFilterSetting.createMany({
          data: newFilters.map(f => ({
            // id is auto-generated by cuid(), so we don't pass it from client for createMany
            pattern: f.pattern,
            description: f.description,
            type: f.type,
            // userId: auth.user.id, // If settings were per-user
          })),
        });
      }
    });

    // Log audit event for group filter update
    await logAuditEvent({
      userId,
      action: 'updateGroupFilters',
      details: { oldFilters, newFilters },
      ipAddress,
      userAgent,
    });

    return NextResponse.json({ message: 'Settings applied successfully' }, { status: 200 });
  } catch (error) {
    logger.error('Failed to apply group filter settings:', error);
    // Check for specific Prisma errors if needed, e.g., validation errors
    return NextResponse.json({ error: 'Failed to Save Settings' }, { status: 500 });
  }
  });
}